# wrangler.toml - 修复版本
name = "telegram-chat-worker"
main = "worker.js"
compatibility_date = "2025-09-06"

# 环境变量
[vars]
ENCRYPTION_KEY = "32byteslongencryptionkey12345678"  # 32字节加密密钥
ADMIN_USERNAME = "xiyue"

# 兼容性标志 - 修正格式：必须是字符串数组
compatibility_flags = ["web_socket"]
